---
sudo: required
language: python

services:
  - docker

install:
  - pip install "ome-ansible-molecule<0.5"

script:
  - molecule test -s $SCENARIO

env:
  - SCENARIO=ice36all
  - SCENARIO=ice36minimal
  - SCENARIO=ice36-ubuntu1804

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
