---
# tasks file for roles/ice

# Note download is handled by the ome.deploy_archive dependency

- name: zeroc ice | dependencies for Ubuntu 18
  become: true
  apt:
    name:
      - libdb5.3
      - libdb5.3++
      - libexpat1
      - libmcpp0
      - openssl
  when:
    - ansible_os_family | lower == 'debian'
    - ansible_distribution_major_version == '18'
    
- name: zeroc ice | dependencies for ubuntu 20
  become: true
  apt:
    name:
      - build-essential
      - db5.3-util
      - libbz2-dev
      - libdb++-dev
      - libdb-dev
      - libexpat-dev
      - libmcpp-dev
      - libssl-dev
      - zlib1g-dev
  when:
    - ansible_os_family | lower == 'debian'
    - ansible_distribution_major_version == '20'       
