---
# tasks file for roles/ice

- name: Load ice variables
  include_vars: ice-{{ ice_version }}.yml

- name: zeroc ice | setup repository
  become: yes
  get_url:
    dest: /etc/yum.repos.d/zeroc-ice-el7.repo
    url: "{{ ice_repourl }}"

- name: zeroc ice | install runtime packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ ice_runtime_packages }}"

- name: zeroc ice | install devel packages
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ ice_devel_packages }}"
  when: 'ice_install_devel | default(True)'

- name: zeroc ice | install ice pip dependencies
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ ice_pip_dependencies }}"
  when: "ice_pip_dependencies and (ice_python_wheel is not defined)"

- name: zeroc ice | pip install packages
  become: yes
  pip:
    name: "{{ ice_pip_packages }}"
    state: present
  when: "ice_pip_packages and (ice_python_wheel is not defined)"

- name: zeroc ice | install python-pip for wheel
  become: yes
  yum:
    name: python-pip
    state: present
  when: "ice_python_wheel is defined"

- name: zeroc ice | install ice wheel package
  become: yes
  pip:
    name: "{{ ice_python_wheel }}"
    state: present
  when: "ice_python_wheel is defined"
