---
# tasks file for roles/ice

- name: zeroc ice | setup repository
  become: true
  get_url:
    dest: /etc/yum.repos.d/zeroc-ice-el7.repo
    url: "https://zeroc.com/download/Ice/3.6/el7/zeroc-ice3.6.repo"

- name: zeroc ice | install runtime packages
  become: true
  yum:
    name: ice-all-runtime
    state: present

- name: zeroc ice | install devel packages
  become: true
  yum:
    name: ice-all-devel
    state: present
  when: ice_install_devel

- name: zeroc ice | install ice pip dependencies
  become: true
  yum:
    name:
      - gcc
      - gcc-c++
      - libdb-utils
      - bzip2-devel
      - expat-devel
      - openssl-devel
      - python-devel
      - python-pip
    state: present
  when: ice_install_python and (ice_python_wheel | length < 1)

- name: zeroc ice | pip install packages
  become: true
  pip:
    name:
      - "zeroc-ice>=3.6,<3.7"
    state: present
  when: ice_install_python and (ice_python_wheel | length < 1)

- name: zeroc ice | install python-pip for wheel
  become: true
  yum:
    name: python-pip
    state: present
  when: ice_install_python and (ice_python_wheel | length >= 1)

- name: zeroc ice | install ice wheel package
  become: true
  pip:
    name: "{{ ice_python_wheel }}"
    state: present
  when: ice_install_python and (ice_python_wheel | length >= 1)
